version: '2'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
#    volumes:
#      - ./rabbitmq/db-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672
